name: CI → Test → Build & Push → Deploy

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build & test
        run: mvn -B clean test

      # 👇 Authenticate to GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      # 👇 Build and push to Artifact Registry
      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        run: |
          IMAGE="us-central1-docker.pkg.dev/pure-sunlight-469209-s3/student-course-repo/student-course-app:latest"
          docker build -t $IMAGE .
          docker push $IMAGE

      # 👇 Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy student-course-app \
            --image=us-central1-docker.pkg.dev/pure-sunlight-469209-s3/student-course-repo/student-course-app:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated