name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd='curl -sS http://localhost:8000/ >/dev/null || exit 1'
          --health-interval=2s
          --health-timeout=2s
          --health-retries=10

    env:
      # Make your code read this to point the SDK to the service
      DYNAMODB_ENDPOINT: http://localhost:8000
      # recommended to tell code it's CI
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Maven - unit tests
        run: mvn -B -DskipITs=true test

      - name: Maven - integration tests (failsafe)
        # failsafe will look for your IntegrationTest/IT classes
        run: mvn -B -DskipITs=false verify

      - name: Archive test reports (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: target/*reports*/**/*.xml
